# SPDX-License-Identifier: GPL-2.0

obj-y             := core.o char.o firmware.o random.o
obj-$(CONFIG_PCI) += pci.o ../../../drivers/pci/pci-driver.o \
		     ../../../drivers/pci/host-bridge.o \
		     ../../../drivers/pci/devres.o \
		     ../../../drivers/pci/access.o \
		     ../../../drivers/pci/search.o \
		     ../../../drivers/pci/probe.o \
		     ../../../drivers/pci/bus.o \
		     ../../../drivers/pci/irq.o \
		     ../../../drivers/pci/vpd.o \
		     ../../../drivers/pci/pci.o \
		     ../../../drivers/pci/rom.o \
		     ../../../drivers/pci/rebar.o \
		     ../../../drivers/pci/vc.o
