obj-y = execmem.o page_alloc.o memblock.o util.o vmalloc.o shmem.o shrinker.o \
	../../../mm/slab_common.o ../../../mm/slub.o \
	../../../mm/percpu.o ../../../mm/debug.o \
	../../../mm/dmapool.o ../../../mm/mempool.o \
	../../../mm/util.o ../../../mm/page_frag_cache.o \
	../../../mm/filemap.o
